// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBQ0GSVMjZnI9U0cDiAkzYcQUlKz6Rxw',
    appId: '1:724565946696:web:31f182b103eb538c4cc37d',
    messagingSenderId: '724565946696',
    projectId: 'learning-flutter-69420',
    authDomain: 'learning-flutter-69420.firebaseapp.com',
    storageBucket: 'learning-flutter-69420.firebasestorage.app',
    measurementId: 'G-6L4VV8KEVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDs7e1g1hLiWNC9CB4_vAew-mDspFS9Q',
    appId: '1:724565946696:android:2a4f6903f7dbd53d4cc37d',
    messagingSenderId: '724565946696',
    projectId: 'learning-flutter-69420',
    storageBucket: 'learning-flutter-69420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALO6UVP8jRGsL2vy33FEHzhQIK9sjsJNU',
    appId: '1:724565946696:ios:22cd716a02feff4a4cc37d',
    messagingSenderId: '724565946696',
    projectId: 'learning-flutter-69420',
    storageBucket: 'learning-flutter-69420.firebasestorage.app',
    iosBundleId: 'com.example.continuelearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALO6UVP8jRGsL2vy33FEHzhQIK9sjsJNU',
    appId: '1:724565946696:ios:22cd716a02feff4a4cc37d',
    messagingSenderId: '724565946696',
    projectId: 'learning-flutter-69420',
    storageBucket: 'learning-flutter-69420.firebasestorage.app',
    iosBundleId: 'com.example.continuelearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwBQ0GSVMjZnI9U0cDiAkzYcQUlKz6Rxw',
    appId: '1:724565946696:web:1d458323311498334cc37d',
    messagingSenderId: '724565946696',
    projectId: 'learning-flutter-69420',
    authDomain: 'learning-flutter-69420.firebaseapp.com',
    storageBucket: 'learning-flutter-69420.firebasestorage.app',
    measurementId: 'G-VGK41M0QMN',
  );

}